dist: precise

language: php

php:
  - '7.2.5'

addons:
  mariadb: '10.4'

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - sudo mysql -e "USE mysql; UPDATE user SET password=PASSWORD('test') WHERE user='root'; FLUSH PRIVILEGES;"
  - sudo mysql -u root --password=test -e 'CREATE DATABASE test;'
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv

script:
  - php artisan test

notifications:
  email: false