name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:10.4
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: test
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env.travis
      run: cp .env.travis .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Running Migrations
      run: php artisan migrate  
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --verbose
      env:
        DB_PORT: ${{ job.services.maridb.ports[3306] }}
